### ISSUE TITLE
Building on a Mac

### ISSUE THREAD

**Issue by mahaarbo** [stonier/cv_backports#4]
Hi, I'm trying to build cv_backports on a Mac OS X El Capitan, but it does not seem to be able to include the necessary Qt libraries.

> In file included from /Users/mathia/Programming/ROS/catkin_ws/src/cv_backports/src/lib/window_QT.cpp:45:
> /Users/mathia/Programming/ROS/catkin_ws/src/cv_backports/src/lib/window_QT.h:50:10: fatal error: 
>       'QAbstractEventDispatcher' file not found
> # include <QAbstractEventDispatcher>
> 
> ```
>      ^
> ```
> 
> 1 error generated.
> make[2]: **\* [cv_backports/src/lib/CMakeFiles/cv_backports.dir/window_QT.cpp.o] Error 1
> make[1]: **\* [cv_backports/src/lib/CMakeFiles/cv_backports.dir/all] Error 2
> make: **\* [all] Error 2

I have Qt installed with homebrew, so the header in question is located in /usr/local/Cellar/qt/4.8.7_2/include/QtCore/. 
I'm not very experienced with these things, is it a result of how find_package is done in CMakeLists?

**Comment by stonier** [comment]
Yes, `find_package(Qt4)` does the work by running a `FindQt4.cmake` module. This is part of the official cmake distribution - e.g. I find it on ubuntu trusty in `/usr/share/cmake-2.8/Modules/FindQt4.cmake`.

If you look at that file, there is alot of info about how it looks up Qt4 in the comments at the top of the file.

Some things you can do - check that you're getting something (or not) in the resulting qt variables, e.g.

```
message(STATUS "QT_INCLUDE_DIR................${QT_INCLUDE_DIR}")
message(STATUS "QT_INCLUDES.....................${QT_INCLUDES}")
message(STATUS "QT4_DEFINITIONS...............${Qt4_DEFINITIONS}")
```

It could be that the find package module is not setting the variables in the same way on the Mac. If this is the case, check some other variables that often get set, e.g. `QT_INCLUDES`, `Qt4_INCLUDE_DIR`, `QT_INCLUDE_DIRS`, `Qt4_INCLUDE_DIRS`.

If none of these are set, check if it actually found Qt4 (it should have, since it got past the find package step) by printing `QT_FOUND`, `Qt4_FOUND`, `QT4_FOUND`.

If it didn't find Qt4, then it is more fundamental, but give the above a try first.

**Comment by mahaarbo** [comment]
Cool, seems it set the correct paths when I checked. 
The trick was to add:
`include(${QT_USE_FILE})`
after the `find_package`. Now it seems to build fine.

**Comment by stonier** [comment]
Yes, that was going to be my next suggestion. I later started adding that to my other qt packages. Interesting that it worked for me out of the box here and also on the build farm.
